Models/DogViewModel.cs
namespace App.Models;

public class DogViewModel
{
    public string? Name { get; set; }
    public int Age { get; set; }
}

Models/ErrorViewModel.cs
namespace App.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/HotelBookingViewModel.cs
namespace App.Models;

public class HotelBookingViewModel
{
    public int Id { get; set; }
    public string? GuestName { get; set; }
    public DateTime DateStart { get; set; }
    public DateTime DateEnd { get; set; }
}

Controllers/HelloController.cs
using App.Models;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers;

public class HelloController : Controller
{
    private static List<DogViewModel> dogs = new List<DogViewModel>();

    public IActionResult Index()
    {
        // var dog = new DogViewModel { Name = "Penis", Age = 3 };
        return View(dogs);
    }

    public IActionResult Create()
    {
        var dog = new DogViewModel();
        return View(dog);
    }

    public IActionResult CreateDog(DogViewModel dogViewModel)
    {
        // return View("Index");
        dogs.Add(dogViewModel);
        return RedirectToAction(nameof(Index)); 
    }
}

Controllers/HomeController.cs
using App.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace App.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/HotelBookingController.cs
using App.Models;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers;

public class HotelBookingController : Controller
{
    public IActionResult HotelBookingDetails()
    {
        var hotel = new HotelBookingViewModel 
        { 
            Id = 1,
            GuestName = "Soldier Boy",
            DateStart = new DateTime(2022, 07, 09), 
            DateEnd = new DateTime(2022, 07, 14)
        };

        return View(hotel);
    }
}

Views/Hello/Create.cshtml
@model App.Models.DogViewModel;

<h1 class="mb-4">Create a Dog!</h1>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h5>My New Doggo</h5>
            </div>

            <div class="card-body">
                <form asp-controller="Hello" asp-action="CreateDog" method="post">
                    <div class="mb-3">
                        <label class="mb-1">Name</label>
                        <input asp-for=Name type="text" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="mb-1">Age</label>
                        <input asp-for=Age type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary mt-3">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    

Views/Hello/Index.cshtml
@model List<App.Models.DogViewModel>

<h1 class="mb-4">Dogs</h1>

<ul>
    @foreach (var dog in Model) {
        <li>Doggo @dog.Name, aged @dog.Age</li>
    }
</ul>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 mb-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/HotelBooking/HotelBookingDetails.cshtml
@model App.Models.HotelBookingViewModel;

<h1 class="mb-4">Hotel Bookings</h1>

<p>@Model.Id: @Model.GuestName, @Model.DateStart.ToShortDateString() to @Model.DateEnd.ToShortDateString()</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/App.styles.css" asp-append-version="true" />

        <title>App</title>
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">App</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Hello" asp-action="Index">Dog List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Hello" asp-action="Create">New Dog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="HotelBooking" asp-action="HotelBookingDetails">Hotel Bookings</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 App &bull; <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>